// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for all platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        // ✅ safer fallback instead of crashing app
        return web;

      default:
        return web;
    }
  }

  // 🌐 WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOV9tuyR3Ifl45QVVzlLPRkNpoFApLuyw',
    appId: '1:148510940246:web:5e5b68bc1f4d7a4ef56ff7',
    messagingSenderId: '148510940246',
    projectId: 'ecommerce-mini-cart-2',
    authDomain: 'ecommerce-mini-cart-2.firebaseapp.com',
    storageBucket: 'ecommerce-mini-cart-2.appspot.com',
  );

  // 🤖 ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJvj_3fWKEl5X75JS5VGQZ7HQ5if_WfA',
    appId: '1:148510940246:android:42a80b9e1c54d1f3f56ff7',
    messagingSenderId: '148510940246',
    projectId: 'ecommerce-mini-cart-2',
    storageBucket: 'ecommerce-mini-cart-2.appspot.com',
  );

  // 🍎 IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbxuAONxNikY1185vYpIfx_GQhUACawZI',
    appId: '1:148510940246:ios:8c648a40fd3f521af56ff7',
    messagingSenderId: '148510940246',
    projectId: 'ecommerce-mini-cart-2',
    storageBucket: 'ecommerce-mini-cart-2.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
